version: "3.8"

x-airflow-common: &airflow-common
  image: airflow-kedro:latest
  environment:
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: "D8mrNFD4HrlsDHdSOLN4yY6t_OLawoFWbotTunOVwqY="
    AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
    AIRFLOW_UID: 50000
  volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../airflow/logs:/opt/airflow/logs
    - ../airflow/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}"
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Construcción única de la imagen
  airflow-base:
    build:
      context: ..
      dockerfile: docker/Dockerfile.airflow
    image: airflow-kedro:latest

  airflow-init:
    <<: *airflow-common
    image: airflow-kedro:latest
    entrypoint: >
      bash -c "airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      echo 'Airflow Init Completed'"

  webserver:
    <<: *airflow-common
    image: airflow-kedro:latest
    command: webserver
    ports:
      - "8080:8080"

  scheduler:
    <<: *airflow-common
    image: airflow-kedro:latest
    command: scheduler

  worker:
    <<: *airflow-common
    image: airflow-kedro:latest
    command: celery worker

  flower:
    <<: *airflow-common
    image: airflow-kedro:latest
    command: celery flower
    ports:
      - "5555:5555"

volumes:
  postgres-db-volume:
 