version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5
    restart: always

  webserver:
    image: apache/airflow:2.10.2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=H3cHMwvsEYxcr5H019NOzDpFipznBsD7UVngceEhcpY=
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - _PIP_ADDITIONAL_REQUIREMENTS=
    volumes:
      - ../conf/airflow/dags:/opt/airflow/dags
      - ../conf/airflow/logs:/opt/airflow/logs
      - ../conf/airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    restart: always
    command: >
      bash -c "airflow db init && \
      airflow users create --username admin --firstname Brandon --lastname Casas --role Admin --email admin@example.com --password admin && \
      airflow webserver"

  scheduler:
    image: apache/airflow:2.10.2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ../conf/airflow/dags:/opt/airflow/dags
      - ../conf/airflow/logs:/opt/airflow/logs
      - ../conf/airflow/plugins:/opt/airflow/plugins
    restart: always
    command: bash -c "airflow scheduler"

volumes:
  postgres-db-volume:
